---
title: "Map_USA"
author: "Maxwel Coura Oliveira"
date: "5/2/2021"
output: html_document
---


```{r}
library(tidyverse)
library(maps)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggspatial)
library(tidyUSDA)
```

```{r}
key <- '7B8DE5D4-8393-3BF2-AAE3-A578DADE4D38'
```

```{r}
soy_row <- tidyUSDA::getQuickstat(
  key = key,
  program = 'SURVEY',
  sector= 'CROPS',
  group= 'FIELD CROPS',
  commodity= 'SOYBEANS',
  category= 'ROW WIDTH',
  domain= 'TOTAL',
  data_item = 'SOYBEANS - ROW WIDTH, MEASURED IN INCHES / ROW',
  geographic_level = 'STATE',
  year = '2020',
  state = NULL,
  county= NULL,
  geometry = TRUE,
  lower48 = TRUE, 
  weighted_by_area = TRUE)
soy_row
```

```{r}
data <- tidyUSDA::getQuickstat(
  key = key,
  program = 'SURVEY',
  sector= 'ENVIRONMENTAL',
  group= 'FIELD CROPS',
  commodity= 'COTTON',
  category= 'TREATED',
  domain= 'CHEMICAL, HERBICIDE',
  data_item = 'COTTON - TREATED, MEASURED IN PCT OF AREA PLANTED, AVG',
  geographic_level = 'STATE',
  year = '2019',
  state = NULL,
  county= NULL,
  geometry = TRUE,
  lower48 = TRUE, 
  weighted_by_area = TRUE)
data
```

```{r}
# Plot this data for each state
tidyUSDA::plotUSDA(df = soy_row)
```


```{r}
world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)
```

```{r}
#add finer administrative information
states <- st_as_sf(map("state", plot = FALSE, fill = TRUE))
head(states)
```

```{r}
states <- cbind(states, st_coordinates(st_centroid(states)))
```

```{r}
# make state Title
library(tools)
states$ID <- toTitleCase(states$ID)
head(states)
```

```{r}
# Old Hawaiian projection (CRS 4135)
(hawaii  <- ggplot(data = usa) +
     geom_sf(fill = "cornsilk") +
     coord_sf(crs = st_crs(4135), xlim = c(-161, -154), ylim = c(18, 
         23), expand = FALSE, datum = NA))

# Alaska Albers projection (CRS 3467)
(alaska <- ggplot(data = usa) +
     geom_sf(fill = "cornsilk") +
     coord_sf(crs = st_crs(3467), xlim = c(-2400000, 1600000), ylim = c(200000, 
         2500000), expand = FALSE, datum = NA))
```




```{r}
#  US National Atlas Equal Area projection (CRS 2163)
usa <- subset(world, admin == "United States of America")
(mainland <- ggplot(data = usa) +
    geom_sf() +
    geom_sf(data = data, aes(fill = Value)) +
    geom_sf(data = states, fill = NA) +
    labs(title = 'Cotton - % of area treated to herbicides') +
    scale_fill_viridis_c(name = "% of area planted", option = "inferno",
#                         limits = c(12, 30), 
#                         breaks = c(15, 20, 25, 30),
                         trans = "sqrt", alpha = .4) +
#    geom_text(data = states, aes(x = X, y = Y, label = ID), size = 5) +
    coord_sf(crs = st_crs(2163), xlim = c(-2500000, 2500000), ylim = c(-2300000, 
         730000))) 
```


```{r}
# Using cowplot
ratioAlaska <- (2500000 - 200000) / (1600000 - (-2400000))
ratioHawaii  <- (23 - 18) / (-154 - (-161))

ggdraw(mainland) +
    draw_plot(alaska, width = 0.26, height = 0.26 * 10/6 * ratioAlaska, 
        x = 0.05, y = 0.05) +
    draw_plot(hawaii, width = 0.15, height = 0.15 * 10/6 * ratioHawaii, 
        x = 0.3, y = 0.05)
```

